Fixes typos in the interpolation test of Scipy library (#430)
# Description

Currently `test_scipy.py` fails with the following error:
```
======================================================================
ERROR: test_interpolation (test_scipy.TestScipyOperations)
Test scipy interpolation 2D method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/orbit/source/extensions/omni.isaac.orbit/test/deps/test_scipy.py", line 58, in test_interpolation
    func_RectBiVariate = interpolate.RectBivariateSpline(y, x, height_field_downsampled)
  File "/isaac-sim/exts/omni.pip.compute/pip_prebundle/scipy/interpolate/_fitpack2.py", line 1494, in __init__
    raise ValueError('x dimension of z must have same number of '
ValueError: x dimension of z must have same number of elements as x

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
There was an error running python
```
#426 changed the argument in `test_scipy.py` but did not change the
ordering to be the correct `(x,y)`. This fixes that.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with
`./orbit.sh --format`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [x] I have run all the tests with `./orbit.sh --test` and they pass
- [ ] I have updated the changelog and the corresponding version in the
extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already
exists there

<!--
As you go through the checklist above, you can mark something as done by
putting an x character in it

For example,
- [x] I have done this task
- [ ] I have not done this task
-->